import { createClientFromRequest } from 'npm:@base44/sdk@0.8.31';
Deno.serve(async (req) => { createClientFromRequest(req); const html = `<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>JSONSuture API Docs</title><style>body{max-width:900px;margin:50px auto;padding:0 20px;font:16px/1.6 system-ui;color:#172033}h1,h2{line-height:1.2}code,pre{font-family:ui-monospace,monospace}pre{background:#0f172a;color:#e2e8f0;padding:18px;border-radius:9px;overflow:auto}table{border-collapse:collapse;width:100%}td,th{padding:10px;border-bottom:1px solid #ddd;text-align:left}a{color:#0369a1}</style></head><body><p><a href="https://vesper-3159a405.base44.app/functions/jsonSutureHome">← JSONSuture</a></p><h1>JSONSuture API v1</h1><p>Deterministically repair malformed JSON and optionally validate the result against JSON Schema. Payloads are not stored.</p><h2>1. Create a free key</h2><pre>curl -X POST https://vesper-3159a405.base44.app/functions/v1CreateKey</pre><p>The raw key is returned once. Free keys include 250 calls/month and 10 calls/minute.</p><h2>2. Repair JSON</h2><pre>curl -X POST https://vesper-3159a405.base44.app/functions/v1RepairJson \\
-H "Authorization: Bearer $JSONSUTURE_API_KEY" \\
-H "Content-Type: application/json" \\
-d '{"text":"{name: Ada, count: 3,}"}'</pre><h2>Request fields</h2><table><tr><th>Field</th><th>Type</th><th>Notes</th></tr><tr><td><code>text</code></td><td>string</td><td>Required; max 128 KiB.</td></tr><tr><td><code>schema</code></td><td>object</td><td>Optional JSON Schema; local <code>$ref</code> only; max 32 KiB.</td></tr><tr><td><code>options.coerce_types</code></td><td>boolean</td><td>Default false.</td></tr><tr><td><code>options.use_defaults</code></td><td>boolean</td><td>Default false.</td></tr></table><h2>JavaScript</h2><pre>const response = await fetch("https://vesper-3159a405.base44.app/functions/v1RepairJson", { method: "POST", headers: {"Authorization": "Bearer " + process.env.JSONSUTURE_API_KEY, "Content-Type": "application/json"}, body: JSON.stringify({text: modelOutput, schema}) });
const result = (await response.json()).result;</pre><h2>Python</h2><pre>import os, requests
r = requests.post("https://vesper-3159a405.base44.app/functions/v1RepairJson", headers={"Authorization": "Bearer " + os.environ["JSONSUTURE_API_KEY"]}, json={"text": model_output, "schema": schema}, timeout=10)
r.raise_for_status()
result = r.json()["result"]</pre><h2>Errors</h2><table><tr><th>Status</th><th>Codes</th></tr><tr><td>400</td><td>INVALID_INPUT, INVALID_SCHEMA, REMOTE_REF_NOT_ALLOWED, UNSAFE_KEY</td></tr><tr><td>401</td><td>UNAUTHORIZED</td></tr><tr><td>402</td><td>QUOTA_EXCEEDED</td></tr><tr><td>413</td><td>PAYLOAD_TOO_LARGE, SCHEMA_TOO_LARGE, PAYLOAD_TOO_DEEP</td></tr><tr><td>422</td><td>UNREPAIRABLE_JSON</td></tr><tr><td>429</td><td>RATE_LIMIT_EXCEEDED</td></tr></table><p>All errors include <code>error.code</code>, <code>error.status</code>, <code>error.detail</code>, and <code>error.request_id</code>.</p><h2>Implementation help</h2><p>For integration guidance, email <a href="mailto:darkstorm13@gmail.com?subject=JSONSuture%20implementation%20help">darkstorm13@gmail.com</a>. Share your stack and expected JSON shape, not secrets or sensitive payloads.</p><h2>Machine-readable</h2><p><a href="https://vesper-3159a405.base44.app/functions/jsonSutureOpenapi">OpenAPI 3.1 JSON</a> · <a href="https://github.com/gilgold/jsonsuture-api/blob/main/llms.txt">llms.txt</a> · <a href="https://github.com/gilgold/jsonsuture-api/blob/main/agent-tool.json">Tool schema</a></p></body></html>`; return new Response(html, { headers: { 'Content-Type':'text/html; charset=utf-8', 'Cache-Control':'public, max-age=300', 'X-Content-Type-Options':'nosniff' } }); });
